// settings.gradle
// Define o nome do projecto e os módulos que o compõem.
// O Android Studio usa este ficheiro para reconhecer a estrutura do projecto.

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "DiarioEmocoes"
include ':app'
